
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="my-theme" lang="en">
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
